// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedEntry = `-- name: CreateFeedEntry :one

INSERT INTO feed(name, url, created_at, updated_at, user_id)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
)
RETURNING id, name, url, created_at, updated_at, user_id
`

type CreateFeedEntryParams struct {
	Name      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.NullUUID
}

func (q *Queries) CreateFeedEntry(ctx context.Context, arg CreateFeedEntryParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeedEntry,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many

SELECT name, url, user_id FROM feed
`

type GetFeedsRow struct {
	Name   string
	Url    string
	UserID uuid.NullUUID
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFeed = `-- name: ResetFeed :exec

DELETE FROM feed *
`

func (q *Queries) ResetFeed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFeed)
	return err
}
