// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedEntry = `-- name: CreateFeedEntry :one

INSERT INTO feed(name, url, created_at, updated_at, user_id)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
)
RETURNING id, name, url, created_at, updated_at, user_id, last_fetched_at
`

type CreateFeedEntryParams struct {
	Name      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.NullUUID
}

func (q *Queries) CreateFeedEntry(ctx context.Context, arg CreateFeedEntryParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeedEntry,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeed = `-- name: GetFeed :one

SELECT id, name, url, created_at, updated_at, user_id, last_fetched_at FROM feed WHERE url = $1
`

func (q *Queries) GetFeed(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many

SELECT name, url, user_id FROM feed
`

type GetFeedsRow struct {
	Name   string
	Url    string
	UserID uuid.NullUUID
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT id, name, url, created_at, updated_at, user_id, last_fetched_at FROM feed
ORDER BY last_fetched_at ASC NULLS FIRST
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const markFeedFetched = `-- name: MarkFeedFetched :exec

UPDATE feed SET last_fetched_at = $1, updated_at = $1
WHERE feed.id = $2
`

type MarkFeedFetchedParams struct {
	LastFetchedAt sql.NullTime
	ID            int64
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, arg.LastFetchedAt, arg.ID)
	return err
}

const resetFeed = `-- name: ResetFeed :exec

DELETE FROM feed *
`

func (q *Queries) ResetFeed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFeed)
	return err
}
